"""Add tables for pet owners, pet sitters, appointments, and pets with validations and relationships

Revision ID: 02e98f340062
Revises: 5f7ed0f6e17b
Create Date: 2025-01-15 13:53:29.272113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02e98f340062'
down_revision = '5f7ed0f6e17b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(), nullable=False),
    sa.Column('_hash_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_name')
    )
    op.create_table('pet_sitters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('pet_owners_id', sa.Integer(), nullable=False),
    sa.Column('pet_sitters_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pet_owners_id'], ['pet_owners.id'], name=op.f('fk_appointments_pet_owners_id_pet_owners')),
    sa.ForeignKeyConstraint(['pet_sitters_id'], ['pet_sitters.id'], name=op.f('fk_appointments_pet_sitters_id_pet_sitters')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pet_name', sa.String(), nullable=False),
    sa.Column('pet_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['pet_owners.id'], name=op.f('fk_pets_owner_id_pet_owners')),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pet_name'),
    sa.UniqueConstraint('pet_type')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pets')
    op.drop_table('appointments')
    op.drop_table('pet_sitters')
    op.drop_table('pet_owners')
    # ### end Alembic commands ###
